import { test, expect } from '@playwright/test';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';

test('public password login, refresh recovery, reader permission and revocable logout', async ({ page, context, browser, baseURL }) => {
  const credentials: { username: string; password: string } = JSON.parse(readFileSync(process.env.CONSOLE_LOGIN_FILE!, 'utf8'));
  const evidence = resolve(process.env.CONSOLE_EVIDENCE_DIR ?? 'docs/evidence'); mkdirSync(evidence, { recursive: true });
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/'); await expect(page.getByLabel('账号', { exact: true })).toBeEnabled();
  await page.screenshot({ path: resolve(evidence, 'public-password-login.png'), fullPage: true });
  await page.getByLabel('账号', { exact: true }).fill(credentials.username);
  await page.getByLabel('密码', { exact: true }).fill('intentionally-incorrect');
  await page.getByRole('button', { name: '进入控制台' }).click();
  await expect(page.getByRole('alert')).toContainText('账号或密码不正确');
  await page.getByLabel('密码', { exact: true }).fill(credentials.password);
  await page.getByRole('button', { name: '进入控制台' }).click();
  await expect(page.getByRole('heading', { name: '采集链路总览', exact: true })).toBeVisible();
  await expect(page.getByText('必需领域已入库', { exact: true })).toBeVisible();
  const sessionCookie = (await context.cookies()).find(cookie => cookie.name === '__Host-crawlsystem-session');
  expect(!!sessionCookie && sessionCookie.httpOnly && sessionCookie.secure && sessionCookie.sameSite === 'Strict').toBe(true);
  await page.reload();
  await expect(page.getByRole('heading', { name: '采集链路总览', exact: true })).toBeVisible();
  await expect(page.getByLabel('密码', { exact: true })).toHaveCount(0);
  await expect(page.getByRole('link', { name: '创建计划' })).toHaveCount(0);
  const browserSecrets = await page.evaluate(() => JSON.stringify({ cookie: document.cookie, local: { ...localStorage }, session: { ...sessionStorage } }));
  expect(browserSecrets.includes(credentials.password) || browserSecrets.includes(sessionCookie!.value)).toBe(false);
  const writeStatus = await page.evaluate(async () => (await fetch('/api/v1/plans', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Console-Request': '1' }, body: JSON.stringify({ request_id: crypto.randomUUID(), fixture_id: 'channel-basic-v1', required_domains: ['ABOUT', 'VIDEO'] }) })).status);
  expect(writeStatus).toBe(403);
  await page.screenshot({ path: resolve(evidence, 'public-password-overview.png'), fullPage: true });
  const csrf = await fetch(baseURL + '/api/v1/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(credentials), signal: AbortSignal.timeout(15_000) });
  expect(csrf.status).toBe(403);
  const foreign = await fetch(baseURL + '/api/v1/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Console-Request': '1', Origin: 'https://unrelated.example' }, body: JSON.stringify(credentials), signal: AbortSignal.timeout(15_000) });
  expect(foreign.status).toBe(403);
  await page.getByRole('button', { name: '退出登录' }).click();
  await expect(page.getByLabel('账号', { exact: true })).toBeEnabled();
  const replay = await fetch(baseURL + '/api/v1/session', { headers: { Cookie: `${sessionCookie!.name}=${sessionCookie!.value}` }, signal: AbortSignal.timeout(15_000) });
  expect(replay.status).toBe(401);
  await page.reload(); await expect(page.getByLabel('密码', { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
  writeFileSync(resolve(evidence, 'public-password-results.json'), JSON.stringify({ verified_at: new Date().toISOString(), url: baseURL, browser: browser.version(), password_login: 'passed', wrong_password: 'rejected', reload_session: 'passed', http_only_secure_cookie: true, reader_write_status: writeStatus, missing_csrf_status: csrf.status, foreign_origin_status: foreign.status, logged_out_cookie_replay_status: replay.status, browser_errors: 0 }, null, 2) + '\n');
});
