apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: console-node-resources
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app: prometheus
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: control
          podSelector:
            matchLabels:
              app.kubernetes.io/name: control-api-preview
      ports:
        - protocol: TCP
          port: 9090
