import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { MinioStore, RawArchive, ArchiveError, type RawUnit } from '../../apps/execution-worker/src/raw-archive.ts';
import { CONTRACT_VERSION } from '@crawlsystem/contracts';
const kubectl = (...args: string[]) => execFileSync('kubectl', args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
const credentials = JSON.parse(kubectl('-n', 'crawler', 'get', 'secret', 'minio-crawl-worker', '-o', 'json')).data;
const decode = (name: string) => Buffer.from(credentials[name], 'base64').toString();
const store = new MinioStore(`http://${kubectl('-n', 'storage', 'get', 'svc', 'minio', '-o', 'jsonpath={.spec.clusterIP}')}:9000`, 'crawl-raw', decode('access_key'), decode('secret_key'));
const owner = { schema_version: CONTRACT_VERSION, workspace_id: 'r2-storage-acceptance', plan_id: randomUUID(), execution_epoch: 1, input_hash: `sha256:${'1'.repeat(64)}`, workflow_id: 'acceptance' };
const signal = new AbortController().signal, channelId = 'acceptance'; let failNotification = true; const messages: string[] = [];
const archive = new RawArchive(store, { async send(topic, _channel, message) { if (failNotification) throw new ArchiveError('publish'); messages.push(JSON.stringify(message)); } });
assert.equal(await archive.reuse(owner, channelId, 'ABOUT', 'channel', signal), null, 'a missing object must be distinguishable from forbidden access');
const unit: RawUnit = { schema_version: 'crawl.unit.v1', owner, channel_id: channelId, step: 'ABOUT', unit_id: 'channel', captured_at: new Date().toISOString(), responses: [], result: { acceptance: true } };
await assert.rejects(archive.save(unit, signal), /publish/);
failNotification = false;
const saved = await archive.reuse(owner, channelId, 'ABOUT', 'channel', signal);
assert.deepEqual(saved?.result, { acceptance: true });
await assert.rejects(archive.save({ ...unit, result: { overwritten: true } }, signal), /storage/, 'a late attempt must not replace the completed unit');
assert.deepEqual((await archive.reuse(owner, channelId, 'ABOUT', 'channel', signal))?.result, { acceptance: true });
await archive.finish(owner, channelId, 'ABOUT', [saved!.reference], signal);
console.log(JSON.stringify({ result: 'PASSED', plan_id: owner.plan_id, checks: ['missing-object', 'put-before-publish', 'lost-notification-recovery', 'conditional-put', 'step-manifest'], notifications: messages.length }));
