apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: keda
---
apiVersion: v1
kind: Namespace
metadata:
  name: db
---
apiVersion: v1
kind: Namespace
metadata:
  name: temporal
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: v1
kind: Namespace
metadata:
  name: analytics
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: crawler
---
apiVersion: v1
kind: Namespace
metadata:
  name: control
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingest
---
apiVersion: v1
kind: Namespace
metadata:
  name: proxy
---
apiVersion: v1
kind: Namespace
metadata:
  name: business
---
apiVersion: v1
kind: Namespace
metadata:
  name: infra-test
