apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: crawler-pg
  namespace: db
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.6
  enableSuperuserAccess: false
  certificates:
    serverAltDNSNames:
    - crawler-pg-pool
    - crawler-pg-pool.db
    - crawler-pg-pool.db.svc
    - crawler-pg-pool.db.svc.cluster.local
  storage:
    storageClass: crawl-pg-local
    size: 30Gi
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 1500m
      memory: 3Gi
  affinity:
    nodeSelector:
      pool.crawlsystem/pg: 'true'
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
  bootstrap:
    initdb:
      database: crawler
      owner: crawler_owner
  postgresql:
    parameters:
      wal_level: logical
      shared_buffers: 1GB
      work_mem: 4MB
      maintenance_work_mem: 128MB
      max_connections: '100'
      max_replication_slots: '10'
      max_wal_senders: '10'
      max_wal_size: 2GB
      max_slot_wal_keep_size: 4GB
      checkpoint_completion_target: '0.9'
      hot_standby_feedback: 'on'
      sync_replication_slots: 'on'
    synchronous:
      method: any
      number: 1
      dataDurability: required
    pg_hba:
    - hostnossl all all all reject
  replicationSlots:
    highAvailability:
      enabled: true
      synchronizeLogicalDecoding: true
  managed:
    roles:
    - name: temporal_svc
      ensure: present
      login: true
      connectionLimit: 45
      passwordSecret:
        name: temporal-login
    - name: dbz_svc
      ensure: present
      login: true
      replication: true
      connectionLimit: 5
      passwordSecret:
        name: dbz-login
    - name: crawler_owner
      ensure: present
      login: true
      connectionLimit: 30
      passwordSecret:
        name: crawler-pg-app
