apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: kafka
  labels:
    strimzi.io/cluster: crawler-kafka
spec:
  replicas: 3
  roles:
  - controller
  - broker
  resources:
    requests:
      cpu: 300m
      memory: 1Gi
    limits:
      cpu: 900m
      memory: 2Gi
  jvmOptions:
    -Xms: 768m
    -Xmx: 768m
  storage:
    type: jbod
    volumes:
    - id: 0
      type: persistent-claim
      size: 12Gi
      class: crawl-kafka-local
      deleteClaim: false
      kraftMetadata: shared
  template:
    pod:
      terminationGracePeriodSeconds: 120
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pool.crawlsystem/kafka
                operator: In
                values:
                - 'true'
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                strimzi.io/cluster: crawler-kafka
                strimzi.io/name: crawler-kafka-kafka
            topologyKey: kubernetes.io/hostname
---
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: crawler-kafka
  namespace: kafka
spec:
  kafka:
    version: 4.3.1
    listeners:
    - name: tls
      port: 9093
      type: internal
      tls: true
      authentication:
        type: scram-sha-512
      networkPolicyPeers:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kafka
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: business
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: infra-test
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: monitoring
    authorization:
      type: simple
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      auto.create.topics.enable: false
      log.retention.hours: 24
      log.retention.bytes: -1
      log.segment.bytes: 67108864
      log.retention.check.interval.ms: 300000
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  entityOperator:
    topicOperator:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
    userOperator:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - s1
  kafkaExporter:
    topicRegex: .*
    groupRegex: .*
    showAllOffsets: true
    resources:
      requests:
        cpu: 20m
        memory: 32Mi
      limits:
        cpu: 150m
        memory: 128Mi
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - s1
